CREATE VIEW UsersLoggedToday AS
SELECT * FROM Users
WHERE YEAR(LastLogin) = YEAR(GETDATE())
	AND MONTH(LastLogin) = MONTH(GETDATE())
	AND DAY(LastLogin) = DAY(GETDATE())

GO

SELECT * FROM UsersLoggedToday